"""Bundled public config defaults for the source-only release.

The private workspace stored these values as YAML/JSON files. The public bundle
tracks only Python files plus README, so these dictionaries preserve the same
final 0702 settings without adding separate config artifacts.
"""

SSL_PRETEXT_CONFIG = {
    "data_path": "../../../데이터셋/caueeg_dataset_final.npy",
    "age_lookup_path": "",
    "out_dir": "../outputs/pretext",
    "splits_path": "",
    "folds": [0, 1, 2, 3, 4],
    "n_splits": 5,
    "seed": 42,
    "epochs": 50,
    "batch_size": 128,
    "lr": 0.0005,
    "weight_decay": 0.0001,
    "huber_delta": 0.5,
    "subject_reg_lambda": 0.1,
    "grad_clip_norm": 1.0,
    "max_batch_loss_abort": 100.0,
    "num_workers": 0,
    "pin_memory": True,
    "backbone_type": "basic_deep_cnn",
    "base_channels": 32,
    "embedding_dim": 128,
    "dropout": 0.3,
    "deep4_batch_norm": True,
    "add_output_layernorm": True,
    "val_frac": 0.1,
    "early_stop_patience": 0,
    "select_by": "val",
    "augment": {"channel_dropout": 0.1, "time_shift": 40, "gaussian_noise": 0.05},
    "input_norm": "channel_robust_zscore",
    "input_clip": 6.0,
    "log_sanity": True,
    "sanity_batch_size": 32,
    "sanity_abort_mae": 30.0,
    "gate_pearson_r": 0.5,
    "gate_mae": 8.0,
}

DOWNSTREAM_V0_CONFIG = {
    "data_path": "../../../데이터셋/caueeg_dataset_final.npy",
    "age_lookup_path": "",
    "out_dir": "../outputs/downstream_v0",
    "pretext_dir": "../outputs/pretext",
    "splits_path": "",
    "variant": "V0",
    "folds": [0, 1, 2, 3, 4],
    "n_splits": 5,
    "seed": 42,
    "epochs": 50,
    "batch_size": 64,
    "lr": 0.0002,
    "weight_decay": 0.0,
    "dropout": 0.3,
    "head_hidden": None,
    "backbone_type": "basic_deep_cnn",
    "backbone_base_channels": 32,
    "backbone_embedding_dim": 128,
    "backbone_add_output_layernorm": True,
    "backbone_drop_path": 0.1,
    "num_workers": 0,
    "pin_memory": True,
    "use_class_weight": True,
    "require_age": False,
    "val_frac": 0.1,
    "early_stop_patience": 0,
    "select_by": "val",
    "select_metric": "macro_f1",
    "augment": None,
    "input_norm": "channel_robust_zscore",
    "input_clip": 6.0,
}

DOWNSTREAM_V1_CONFIG = {
    **DOWNSTREAM_V0_CONFIG,
    "out_dir": "../outputs/downstream_v1",
    "variant": "V1",
}

SWEEP_CATALOG = {
    "main_basicdeep_smoke": {
        "description": (
            "Fast smoke test of the 0702 main model. Same basic_deep_cnn "
            "architecture as the final run, but short epochs/fold 0 only. "
            "Not for reporting."
        ),
        "variants": ["V0", "V1"],
        "pretext": {
            "backbone_type": "basic_deep_cnn",
            "base_channels": 32,
            "embedding_dim": 128,
            "dropout": 0.3,
            "add_output_layernorm": True,
            "epochs": 3,
            "batch_size": 128,
            "lr": 0.0005,
            "weight_decay": 0.0001,
            "early_stop_patience": 0,
            "val_frac": 0.1,
            "select_by": "val",
            "augment": {"channel_dropout": 0.1, "time_shift": 40, "gaussian_noise": 0.05},
            "input_norm": "channel_robust_zscore",
            "input_clip": 6.0,
            "sanity_abort_mae": 0.0,
            "gate_pearson_r": -1.0,
            "gate_mae": 999.0,
            "num_workers": 0,
            "pin_memory": False,
        },
        "downstream": {
            "backbone_type": "basic_deep_cnn",
            "backbone_base_channels": 32,
            "backbone_embedding_dim": 128,
            "backbone_add_output_layernorm": True,
            "epochs": 3,
            "batch_size": 64,
            "lr": 0.0002,
            "weight_decay": 0.0,
            "dropout": 0.3,
            "head_hidden": None,
            "num_workers": 0,
            "pin_memory": False,
            "use_class_weight": True,
            "require_age": False,
            "val_frac": 0.1,
            "early_stop_patience": 0,
            "select_by": "val",
            "select_metric": "macro_f1",
            "augment": None,
            "input_norm": "channel_robust_zscore",
            "input_clip": 6.0,
        },
    },
    "main_basicdeep": {
        "description": (
            "0702 final main experiment. Deep plain 1-D CNN (basic_deep_cnn), "
            "base_channels=32. V0 and V1 share folds, splits, pretext run, "
            "and all downstream hyperparameters; the only experimental "
            "difference is SSL pretext initialization."
        ),
        "variants": ["V0", "V1"],
        "pretext": {
            "backbone_type": "basic_deep_cnn",
            "base_channels": 32,
            "embedding_dim": 128,
            "dropout": 0.3,
            "add_output_layernorm": True,
            "epochs": 50,
            "batch_size": 128,
            "lr": 0.0005,
            "weight_decay": 0.0001,
            "huber_delta": 0.5,
            "subject_reg_lambda": 0.1,
            "grad_clip_norm": 1.0,
            "max_batch_loss_abort": 100.0,
            "val_frac": 0.1,
            "early_stop_patience": 0,
            "select_by": "val",
            "augment": {"channel_dropout": 0.1, "time_shift": 40, "gaussian_noise": 0.05},
            "input_norm": "channel_robust_zscore",
            "input_clip": 6.0,
            "sanity_abort_mae": 0.0,
            "gate_pearson_r": -1.0,
            "gate_mae": 999.0,
            "num_workers": 0,
            "pin_memory": True,
        },
        "downstream": {
            "backbone_type": "basic_deep_cnn",
            "backbone_base_channels": 32,
            "backbone_embedding_dim": 128,
            "backbone_add_output_layernorm": True,
            "epochs": 50,
            "batch_size": 64,
            "lr": 0.0002,
            "weight_decay": 0.0,
            "dropout": 0.3,
            "head_hidden": None,
            "num_workers": 0,
            "pin_memory": True,
            "use_class_weight": True,
            "require_age": False,
            "val_frac": 0.1,
            "early_stop_patience": 0,
            "select_by": "val",
            "select_metric": "macro_f1",
            "augment": None,
            "input_norm": "channel_robust_zscore",
            "input_clip": 6.0,
        },
    },
}


CONFIG_BY_BASENAME = {
    "ssl_pretext.yaml": SSL_PRETEXT_CONFIG,
    "downstream_v0.yaml": DOWNSTREAM_V0_CONFIG,
    "downstream_v1.yaml": DOWNSTREAM_V1_CONFIG,
}
